export { createDefaultState, getToothPresence } from "./defaults.js";
export {
  OdontogramError,
  OdontogramValidationError,
  VALIDATION_CODES,
  type ValidationCode,
} from "./errors.js";
export {
  createMark,
  filterMarks,
  getMarksForSurface,
  getMarksForTooth,
  markMatchesFilter,
  getMarkTargetSurfaces,
  getMarkTargetTeeth,
  isComplexTarget,
  isMultiToothMark,
  isMultiToothTarget,
  isSurfaceMark,
  isSurfaceTarget,
  isWholeToothMark,
  isWholeToothTarget,
  normalizeMark,
  normalizeMarks,
  normalizeTarget,
} from "./marks.js";
export {
  createValidator,
  deepClone,
  isDeepEqual,
  RULE_MARK_COEXISTENCE,
  RULE_MARK_ID_UNIQUE,
  RULE_OPTIONS_VALIDITY,
  RULE_SELECTION_INTEGRITY,
  RULE_SURFACE_APPLICABILITY,
  RULE_TARGET_INTEGRITY,
  RULE_TEETH_OVERLAY_INTEGRITY,
  RULE_TOOTH_CATALOG_VALIDITY,
  RULE_TOOTH_PRESENCE_COEXISTENCE,
  RULE_UNKNOWN_MARK_TYPE,
  validateMark,
  validateMarks,
  validateOdontogramState,
  validateOptions,
} from "./validation.js";
export {
  CONTROLLED_MODE_EXAMPLE,
  MULTI_MARK_COEXISTENCE_EXAMPLE,
  MULTI_SURFACE_RESTORATIONS_EXAMPLE,
  MULTI_TOOTH_ANNOTATIONS_EXAMPLE,
  SERIALIZATION_EXAMPLES,
  UNKNOWN_MARK_PRESERVATION_EXAMPLE,
  WHOLE_TOOTH_MARKS_EXAMPLE,
} from "./examples.js";
export { Odontogram } from "./odontogram.js";
export { createPlugin } from "./plugin.js";
export type {
  BatchOptions,
  AnnotationHookArg,
  AnnotationContext,
  ComplexTarget,
  CustomContent,
  CustomValidationRule,
  MarkClassNamesArg,
  MarkFilter,
  MarkInput,
  MarkMountArg,
  MarkStatus,
  HookCleanup,
  MarkStyle,
  MarkTarget,
  MarksSetArg,
  MultiToothTarget,
  MultiToothTargetEntry,
  Notation,
  OdontographicMark,
  OdontogramMode,
  OdontogramOptions,
  OdontogramPlugin,
  OdontogramPluginDef,
  OdontogramState,
  ResetOptions,
  SelectionChangeArg,
  SelectionState,
  SetStateOptions,
  SetToothStateOptions,
  StateChangeArg,
  StateChangeSource,
  SurfaceClickArg,
  SurfaceContext,
  SurfaceHookArg,
  SurfaceId,
  ToothClassNamesArg,
  ToothContext,
  ToothLabelContext,
  ToothClickArg,
  ToothId,
  ToothMountArg,
  ToothPresence,
  ToothState,
  ToothStateChangeArg,
  ToothSurfaceTarget,
  ValidationChangeArg,
  ValidationContext,
  ValidationIssue,
  ValidationResult,
  ValidationSeverity,
  ValidatorConfig,
  ViewDefinition,
  ViewContext,
  ViewMountArg,
  ViewOptions,
  ViewRenderContext,
  ViewType,
  WholeToothTarget,
} from "./types.js";
