import { createPlugin } from "@odontogram/core";
import {
  destroySchematicView,
  exportSchematicView,
  renderSchematicView,
  updateSchematicView,
} from "./schematic-view.js";

export const svgPlugin = createPlugin({
  id: "@odontogram/svg",
  version: "0.1.0",
  apiCompatibility: "^1.0.0",
  views: [
    {
      type: "permanent",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "deciduous",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "primary",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "mixed",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "arch",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "upper",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "lower",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "maxillary",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "mandibular",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "quadrant",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "quadrant-1",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "quadrant-2",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "quadrant-3",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "quadrant-4",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "quadrant-5",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "quadrant-6",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "quadrant-7",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "quadrant-8",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "tooth",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
    {
      type: "tooth-detail",
      render: renderSchematicView,
      update: updateSchematicView,
      destroy: destroySchematicView,
      exportSvg: exportSchematicView,
    },
  ],
});

export {
  renderSchematicView,
  updateSchematicView,
  destroySchematicView,
  exportSchematicView,
  createFacePath,
  getArchTeeth,
  layoutArch,
  computeMixedLayout,
  computeViewLayout,
  resolveMarkFill,
  type ToothLayout,
} from "./schematic-view.js";

export { IncrementalSvgRenderer } from "./incremental-renderer.js";

export {
  exportSvg,
  exportPng,
  printOdontogram,
  getPrintMarkup,
  generateStandaloneSvg,
  generateStandaloneStyles,
  resolveExportView,
  type StandaloneSvgExtra,
} from "./export.js";
