export {
  getAllToothRecords,
  getApplicableSurfaces,
  getArch as getAnatomicalArch,
  getDeciduousTeeth,
  getDentition,
  getMixedTeeth,
  getPermanentTeeth,
  getPosition,
  getPredecessor,
  getPrimaryTeeth,
  getQuadrant as getToothQuadrant,
  getSuccessor,
  getTeethForView,
  getTooth,
  isDeciduousTooth,
  isPermanentTooth,
  isPrimaryTooth,
  isSurfaceApplicableToTooth,
  isValidToothId,
  listTeeth,
  type DentitionView,
  type ListTeethOptions,
  type ToothRecord,
} from "./catalog.js";
export {
  fromLayoutArch,
  getArchFromQuadrant,
  getDentitionFromQuadrant,
  isPatientRightQuadrant,
  isPermanentQuadrant,
  isPrimaryQuadrant,
  parseToothId,
  toLayoutArch,
  type ArchId,
  type DentitionId,
  type LayoutArchId,
  type PositionId,
  type QuadrantId,
  type ToothClass,
  type ToothId,
} from "./ids.js";
export {
  fdiAdapter,
  fromNotation,
  getArch,
  getLayoutArch,
  getNotationAdapter,
  getQuadrant,
  isValidNotation,
  listSupportedNotations,
  palmerAdapter,
  SUPPORTED_NOTATIONS,
  toAccessibleNotation,
  toNotation,
  TOOTH_NOTATION_TABLE,
  universalAdapter,
  type Notation,
  type NotationAdapter,
  type ToothNotationRecord,
} from "./notation.js";
export {
  mapFaceToSurface,
  mapSurfaceToFace,
  type GraphicFace,
  type GraphicProjection,
} from "./orientation.js";
export {
  ANTERIOR_SURFACES,
  CLINICAL_SURFACE_CODES,
  getApplicableSurfacesForClass,
  isValidSurface,
  POSTERIOR_SURFACES,
  SURFACE_CODES,
  SURFACE_LABELS,
  type ClinicalSurface,
  type SurfaceCode,
} from "./surfaces.js";
